--liquibase formatted sql

--changeset pixels:pixels-player-0009-add-badge-projection
alter table player_badges add column id bigint generated by default as identity;
alter table player_badges add constraint player_badges_id_uk unique(id);
alter table player_badges add column slot smallint;

with equipped as (
    select player_id,code,row_number() over(partition by player_id order by code)::smallint as slot
    from player_badges
    where equipped
)
update player_badges badge
set slot=equipped.slot
from equipped
where badge.player_id=equipped.player_id and badge.code=equipped.code;

alter table player_badges add constraint player_badges_slot_chk
    check (slot is null or slot between 1 and 5);
alter table player_badges add constraint player_badges_equipped_slot_chk
    check (equipped=(slot is not null));
create unique index player_badges_player_slot_uk on player_badges(player_id,slot) where slot is not null;

--rollback drop index if exists player_badges_player_slot_uk; alter table player_badges drop constraint if exists player_badges_equipped_slot_chk; alter table player_badges drop constraint if exists player_badges_slot_chk; alter table player_badges drop column if exists slot; alter table player_badges drop constraint if exists player_badges_id_uk; alter table player_badges drop column if exists id;
