--liquibase formatted sql

--changeset pixels:pixels-player-0010-user-remaining
create table player_settings (
    player_id bigint primary key references players(id) on delete cascade,
    volume_system smallint not null default 100 check (volume_system between 0 and 100),
    volume_furniture smallint not null default 100 check (volume_furniture between 0 and 100),
    volume_trax smallint not null default 100 check (volume_trax between 0 and 100),
    old_chat boolean not null default false,
    camera_follow_blocked boolean not null default false,
    safety_locked boolean not null default false,
    updated_at timestamptz not null default now(),
    version bigint not null default 1 check (version > 0)
);

create table player_profile_tags (
    player_id bigint not null references players(id) on delete cascade,
    position smallint not null check (position between 1 and 5),
    tag text not null check (char_length(tag) between 1 and 32),
    primary key (player_id, position)
);

create table player_respect_grants (
    actor_player_id bigint not null references players(id) on delete cascade,
    target_player_id bigint not null references players(id) on delete cascade,
    grant_date date not null,
    source text not null default 'user',
    created_at timestamptz not null default now(),
    primary key (actor_player_id, target_player_id, grant_date),
    constraint player_respect_grants_not_self_chk check (actor_player_id <> target_player_id)
);

create index player_respect_grants_actor_day_idx on player_respect_grants(actor_player_id, grant_date);

create table player_wardrobe_outfits (
    player_id bigint not null references players(id) on delete cascade,
    slot_id smallint not null check (slot_id between 1 and 10),
    figure text not null check (char_length(figure) between 1 and 512),
    gender text not null check (gender in ('M', 'F')),
    updated_at timestamptz not null default now(),
    primary key (player_id, slot_id)
);

create table player_name_changes (
    id bigint generated by default as identity primary key,
    player_id bigint not null references players(id) on delete cascade,
    old_username text not null,
    new_username text not null,
    actor_player_id bigint not null references players(id),
    reason text not null,
    source text not null,
    changed_at timestamptz not null default now()
);

create index player_name_changes_player_idx on player_name_changes(player_id, changed_at desc);
create unique index player_profile_tags_value_uidx on player_profile_tags(player_id,lower(tag));

--rollback drop index if exists player_profile_tags_value_uidx; drop index if exists player_name_changes_player_idx; drop table if exists player_name_changes; drop table if exists player_wardrobe_outfits; drop index if exists player_respect_grants_actor_day_idx; drop table if exists player_respect_grants; drop table if exists player_profile_tags; drop table if exists player_settings;
