--liquibase formatted sql

--changeset pixels:gamecenter-0001
create table game_center_games (
    id integer generated by default as identity primary key,
    name text not null,
    bg_color varchar(6) not null default '000000',
    text_color varchar(6) not null default 'ffffff',
    asset_url text not null default '',
    support_url text not null default '',
    launch_url text not null default '',
    launch_kind text not null default 'url' check (launch_kind in ('url', 'params')),
    enabled boolean not null default true,
    version bigint not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table game_center_scores (
    game_id integer not null references game_center_games(id),
    player_id bigint not null references players(id),
    year integer not null,
    week integer not null check (week between 1 and 53),
    score bigint not null,
    updated_at timestamptz not null default now(),
    primary key (game_id, player_id, year, week)
);

create index game_center_scores_leaderboard_idx on game_center_scores (game_id, year, week, score desc, player_id);

--rollback drop table game_center_scores;
--rollback drop table game_center_games;
