package openapi

import "github.com/swaggest/openapi-go/openapi3"

// routeTags returns the user-facing OpenAPI sections in display order.
func routeTags() []openapi3.Tag {
	return []openapi3.Tag{
		tag("Public", "Health checks and development documentation available without authentication."),
		tag("WebSocket", "Pixel-protocol WebSocket connection entrypoint."),
		tag("Client Configuration", "Public Nitro configuration and localized text resources."),
		tag("SSO", "Single-sign-on ticket creation and lifecycle."),
		tag("Players", "Player identities, profiles, settings, and account lifecycle."),
		tag("Player Effects", "Effect inventory, grants, activation, and revocation."),
		tag("Bots", "Bot support state, recovery, and bartender serve items."),
		tag("Pets", "Pet lifecycle, ownership, location, statistics, and runtime metrics."),
		tag("Pet Reference", "Pet species, breeds, commands, and reference-cache refresh."),
		tag("Camera", "Camera pricing, settings, and player captures."),
		tag("Photo Gallery", "Published photos and photo-furniture moderation."),
		tag("Achievements", "Achievement definitions, levels, player progress, and badges."),
		tag("Talents", "Talent-track definitions and player talent levels."),
		tag("Quests", "Quest campaigns, definitions, and player quest state."),
		tag("Quizzes", "Quizzes, questions, results, and room word polls."),
		tag("Badge Promotions", "Badge-promotion definitions, claims, and delivery."),
		tag("Progression", "Progression cache reload and operational metrics."),
		tag("Game Center", "External Game Center registrations and weekly scores."),
		tag("Room Polls", "Room-poll definitions and room assignments."),
		tag("Room Games", "Room-game scores and operational game controls."),
		tag("Groups", "Social-group identity, badge, ownership, and home-room configuration."),
		tag("Group Members", "Group memberships, join requests, roles, and favorites."),
		tag("Group Forums", "Group forum settings, threads, posts, and moderation."),
		tag("Crafting", "Crafting altars, recipes, and player recipe knowledge."),
		tag("Recycler", "Recycler configuration and prize pools."),
		tag("Connections", "Live connection inspection and disconnection."),
		tag("Notifications", "Localized messages delivered to online players."),
		tag("Currencies", "Currency definitions and player wallet mutations."),
		tag("Catalog Pages", "Catalog page structure and publication refresh."),
		tag("Catalog Offers", "Catalog offers and uncovered furniture definitions."),
		tag("Catalog Vouchers", "Voucher definitions and redemption history."),
		tag("Memberships", "Player HC and VIP membership lifecycle."),
		tag("Club Offers", "HC and VIP purchase offers."),
		tag("Targeted Offers", "Player-targeted commercial offers."),
		tag("Calendar", "Seasonal calendar campaigns."),
		tag("Chat Filters", "Global word-filter configuration."),
		tag("Chat Bubbles", "Chat bubble threshold configuration."),
		tag("Chat History", "Bounded room and player chat history."),
		tag("Permissions", "Permission nodes, groups, memberships, grants, and checks."),
		tag("Rooms", "Room records, settings, and metadata."),
		tag("Room Runtime", "Live occupancy, rollers, closing, forwarding, and teleportation."),
		tag("Room Promotions", "Active room promotion inspection and cancellation."),
		tag("Room Bundles", "Room bundle templates and catalog-backed previews."),
		tag("Room Audit", "Room rights, sanctions, and moderation history."),
		tag("Room Votes", "Permanent room upvotes."),
		tag("Navigator", "Navigator categories, lifted rooms, history, favorites, and official rooms."),
		tag("Friends & Privacy", "Friendship inspection, removal, requests, and messenger privacy."),
		tag("Player Trading", "Direct-trade audit and player trading locks."),
		tag("Marketplace", "Marketplace listing intervention."),
		tag("Punishments", "Player punishment history, application, and revocation."),
		tag("Moderation", "Moderation issue queue and case handling."),
		tag("Moderation Settings", "Call-for-help topics, presets, and sanction ladder."),
		tag("WIRED", "WIRED registry, room graphs, diagnostics, and reload controls."),
		tag("Fallback", "Authenticated fallback behavior."),
	}
}
